export const images = {
  articles: {
    articleDiet: require('./articles/article_diet.jpg'),
    articleExercise: require('./articles/article_exercise.jpg'),
    articleMental: require('./articles/article_mental.jpg'),
    articleSleep: require('./articles/article_sleep.jpg'),
  },
  common: {
    facebookLogo: require('./common/facebook_logo.png'),
    googleLogo: require('./common/google-logo.png'),
    googleLogo: require('./common/google_logo.png'),
    healthcareLogo: require('./common/healthcare-logo.png'),
    homeDoctor: require('./common/home_doctor.png'),
    noData: require('./common/no_data.png'),
    splashNew: require('./common/splash-new.png'),
  },
  doctors: {
    doctor1: require('./doctors/doctor_1.jpg'),
    doctor10b: require('./doctors/doctor_10b.jpg'),
    doctor11: require('./doctors/doctor_11.jpg'),
    doctor12b: require('./doctors/doctor_12b.jpg'),
    doctor13b: require('./doctors/doctor_13b.jpg'),
    doctor14: require('./doctors/doctor_14.jpg'),
    doctor15: require('./doctors/doctor_15.jpg'),
    doctor2: require('./doctors/doctor_2.jpg'),
    doctor3: require('./doctors/doctor_3.jpg'),
    doctor4b: require('./doctors/doctor_4b.jpg'),
    doctor5: require('./doctors/doctor_5.jpg'),
    doctor6b: require('./doctors/doctor_6b.jpg'),
    doctor7: require('./doctors/doctor_7.jpg'),
    doctor8: require('./doctors/doctor_8.jpg'),
    doctor9: require('./doctors/doctor_9.jpg'),
    drArun: require('./doctors/dr_arun.jpg'),
    drKumar: require('./doctors/dr_kumar.jpg'),
    drPriya: require('./doctors/dr_priya.jpg'),
  },
  hospitals: {
    hospitalCity: require('./hospitals/hospital_city.jpg'),
    hospitalKurunji: require('./hospitals/hospital_kurunji.jpg'),
    hospitalManipal: require('./hospitals/hospital_manipal.jpg'),
    hospitalSks: require('./hospitals/hospital_sks.jpg'),
  },
  onboarding: {
    onboarding1: require('./onboarding/onboarding-1.png'),
    onboarding2: require('./onboarding/onboarding-2.png'),
  },
};
